nina:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 2632265922
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucket-name: nina1
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx83ac30735c7a8d26
    secret: 9b57e666bdb81d443a780064ed443427